server:
  port: 8088
  servlet:
    context-path:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lhx_csdn?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  # SQL初始化配置
  sql:
    init:
      mode: always  # 总是执行初始化SQL
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      platform: mysql
      continue-on-error: true  # 如果表已存在，继续执行

  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/

  data:
    redis:
      host: localhost
      port: 6379


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lhxcsdn.demo.pojo.entity
  configuration:
    map-underscore-to-camel-case: true # ??????????